events:
  - name: ukraine-de
    db_id: ukraine
    target_folder: 'Twitter/German/'
  - name: ukraine-en
    db_id: ukraine-en
    target_folder: 'Twitter/English/'
  - name: ukraine-ru
    db_id: ukraine-ru
    target_folder: 'Twitter/Russian/'
  - name: ukraine-uk
    db_id: ukraine-uk
    target_folder: 'Twitter/Ukrainian/'
  - name: ukraine-en-hashtag
    db_id: ukraine-en-hashtag
    target_folder: 'Twitter/English-Hashtag'
