events:
  - name: ukraine-de
    db_id: ukraine
    target_folder: 'Twitter/German/'
  - name: ukraine-ru
    db_id: ukraine-ru
    target_folder: 'Twitter/Russian/'
  - name: ukraine-uk
    db_id: ukraine-uk
    target_folder: 'Twitter/Ukrainian/'
  - name: ukraine-en-hashtag
    db_id: ukraine-en-hashtag
    target_folder: 'Twitter/English-Hashtag/'
  - name: bucha-en
    db_id: bucha-en
    target_folder: 'Twitter/Bucha-English/'
  - name: bucha-de
    db_id: bucha-de
    target_folder: 'Twitter/Bucha-German/'
  - name: bucha-uk
    db_id: bucha-uk
    target_folder: 'Twitter/Bucha-Ukrainian/'
  - name: bucha-ru
    db_id: bucha-ru
    target_folder: 'Twitter/Bucha-Russian/'
